### ISSUE TITLE
slight fix to README ref adding new email with bin/inbox-auth command

### ISSUE THREAD

**Issue by Analect** [nhurel/nylas-sync-engine#1]
Thanks for this great resource ... and the N1 builder too.

In your step under **Account creation** ... when placed into the container with the `docker exec` command, you are default as root ...

I found that I first had to `su - inbox` (change to user inbox from root) in order to be able to run `bin/inbox-auth your.address@gmail.com`

It might be worth highlight for others not familiar.

**Comment by nhurel** [comment]
Thanks for your feedback.

README has been updated to add this precision.
