### ISSUE TITLE
Is config.json used to control settings for the mysql database?

### ISSUE THREAD

**Issue by Analect** [nhurel/nylas-sync-engine#10]
@nhurel 
I wanted to confirm if config.json was used to control settings in the mysql database?
I'm looking to enable a row-level binlog with something I'm experimenting with here and was wondering if settings like those below would get added into the config.json or not ... or would this get handled as part of the Dockerfile?

```
server-id         = 223344
log_bin           = mysql-bin
binlog_format     = row
expire_logs_days  = 10
```

Thanks again for maintaining a great solution for the sync-engine.

**Comment by nhurel** [comment]
Hi,

`config.json` is a config file for the sync-engine only. It contains information to join the database but that's all.
If you want to finely tune your mysql instance, then you should have a look at the mysql docker image documentation (https://hub.docker.com/_/mysql/). They explain how you can use a custom `my.cnf` config file or how to set configuration at container startup.

HTH

**Comment by Analect** [comment]
Thanks for clarifying.
