### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by miguelrs** [nhurel/nylas-sync-engine#15]
Hi, thanks a lot for spending your time in this project!

Sorry this is probably a dumb question - I don't know much about security and I've never even used Docker before, but I've read that the main issue when running your own Sync Engine is the lack of security.

So let's say I install the Docker app on my Mac/PC, I install this image, and I connect some email accounts to access them locally... are there any security risks involving my emails? and is there anything I can/should do to increase the security level?

**Comment by nhurel** [comment]
Hi,

If you're running it locally you are quite safe. To enforce the security, make sure to expose the port 5555 on your local interface only. This means you should replace the `ports` entry in the docker-compose file by : 
```
ports:
  - 127.0.0.1:5555:5555
```
By default, the ports are exposed on all interfaces, which means that someone in the same network than you could access your local N1 api (when sharing the same wifi network for example) 
By exposing the port on the local interface only, the api is only accessible from applications running on your laptop. So only your local N1 client should be able to access your mails.

**Comment by miguelrs** [comment]
Thanks for your quick help! I've been giving it a try and I could get it up and running - nice work! 👍 

Maybe, if you have time at some point, you could add something about how to stay as safe as possible (both locally or in a server) into the Readme (maybe just useful links can do the work), because I know this is one of the main concerns, and many people (like myself) may be a bit scared of this - mainly because of the lack of knowledge about Docker and security itself 😅
