### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by lunarboy** [nhurel/nylas-sync-engine#16]
Apologies because I am a Docker newbie. But when I get to the account creation step, I'm unable to successfully execute this command:
`sudo -u inbox bin/inbox-auth myemail@email.com`

The output I get is:
`[WARNING] {"level": "warning", "timestamp": "2016-12-09T23:07:02.156078Z", "module": "contextlib:35", "greenlet_id": 140301204586736, "original_exception": "<class 'sqlalchemy.exc.OperationalError'>", "event": "Encountered OperationalError on rollback"}
[ERROR] {"error": "OperationalError", "error_tb": "Traceback (most recent call last):\n  File \"bin/inbox-auth\", line 69, in <module>\n    main()\n  File \"/usr/local/lib/python2.7/dist-packages/click/core.py\", line 488, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/click/core.py\", line 474, in main\n    self.invoke(ctx)\n  File \"/usr/local/lib/python2.7/dist-packages/click/core.py\", line 659, in invoke\n    ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/lib/python2.7/dist-packages/click/core.py\", line 325, in invoke\n    return callback(*args, **kwargs)\n  File \"bin/inbox-auth\", line 39, in main\n    email_address=email_address).first()\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2659, in first\n    ret = list(self[0:1])\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2457, in __getitem__\n    return list(res)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2761, in __iter__\n    return self._execute_and_instances(context)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2774, in _execute_and_instances\n    close_with_result=True)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2765, in _connection_from_session\n    **kw)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py\", line 893, in connection\n    execution_options=execution_options)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py\", line 898, in _connection_for_bind\n    engine, execution_options)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py\", line 334, in _connection_for_bind\n    conn = bind.contextual_connect()\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 2039, in contextual_connect\n    self._wrap_pool_connect(self.pool.connect, None),\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 2078, in _wrap_pool_connect\n    e, dialect, self)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1405, in _handle_dbapi_exception_noconnection\n    exc_info\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py\", line 202, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 2074, in _wrap_pool_connect\n    return fn()\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 376, in connect\n    return _ConnectionFairy._checkout(self)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 713, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 480, in checkout\n    rec = pool._do_get()\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 1060, in _do_get\n    self._dec_overflow()\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py\", line 60, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 1057, in _do_get\n    return self._create_connection()\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 323, in _create_connection\n    return _ConnectionRecord(self)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 449, in __init__\n    self.connection = self.__connect()\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 607, in __connect\n    connection = self.__pool._invoke_creator(self)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py\", line 97, in connect\n    return dialect.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py\", line 385, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py\", line 81, in Connect\n    return Connection(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py\", line 204, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\nOperationalError: (_mysql_exceptions.OperationalError) (1045, \"Access denied for user 'root'@'172.17.0.5' (using password: YES)\")\n", "timestamp": "2016-12-09T23:07:02.163743Z", "error_message": "(_mysql_exceptions.OperationalError) (1045, \"Access denied for user 'root'@'172.17.0.5' (using password: YES)\")", "module": "nylas.logging.log:149", "greenlet_id": 140301204586736, "level": "error"}`

Help? Thanks!

**Comment by nhurel** [comment]
Hi,
it looks like a mysql connection issue : `Access denied for user 'root'@'172.17.0.5' (using password: YES)`

How did you setup your containers ?  Did you follow the "First run" instructions described in the README ?

**Comment by lunarboy** [comment]
Thank you. I did follow the instructions as best as I could. 

After downloading your image, I copied your docker-compose.yml file onto my host and then ran:
`docker-compose up -d mysql`
And then:
`docker-compose up -d`

The containers created were named nylas_mysql_1, nylas_redis_1, and nylas_sync-engine_1.

My next command was:
`docker exec -it nylas_sync-engine_1 bash`

And then:
`sudo -u inbox bin/inbox-auth your.address@gmail.com`
(I added a space between "-u" and "inbox" because it looked like a typo, although it might not be! And of course I replaced "your.address@gmail.com" with my Google email address.

Thanks again for the help.

**Comment by nhurel** [comment]
So... did it work or are you still stuck ?

**Comment by lunarboy** [comment]
Nope, I'm still stuck. Tried it a couple of times.

**Comment by nhurel** [comment]
ok, assuming you've used the same volume names as in the example, can you retry this to be sure you're in a clean state : 
```
docker-compose stop && docker-compose rm -fv
docker volume rm nylas_part nylas_mysql nylas_redis
```
Then repeat the "first run" instructions as you did.

**Comment by lunarboy** [comment]
It's working!

What I missed the first time was the Database Initialization step because I thought it was optional (I assumed that the db was actually initialized). 

Thanks so much for the help!

**Comment by nhurel** [comment]
Great ! 
Happy you sorted your issue :)
