### ISSUE TITLE
Problems with overriding startup command

### ISSUE THREAD

**Issue by tino** [nhurel/nylas-sync-engine#3]
You don't seem to be using `CMD` or `ENTRYPOINT` in your Dockerfile, which causes troubles when trying to run an interactive session. `docker run --rm -it nhurel/nylas-sync-engine bash` still wants to run the startup script while it shouldn't.

**Comment by nhurel** [comment]
Entrypoint is defined by nhurel/ubuntu-s6 (parent image) to `/sbin/s6-svscan -t 0 /etc/s6` to have s6 starting services declared in the container.
You should not need to start this container with another command. If you need to debug a running container, you can run `docker exec -it containername bash` (where containername is the ID or name given by docker when you started the container).

However, if you really want to start the container without starting s6, you can use the `--entrypoint` flag like : 
`docker run --entrypoint=/bin/bash -it --rm nhurel/nylas-sync-engine`

Finally, you can use `docker inspect` command whenever you want to find info about an image or a container such as its entrypoint, cmd or environment variables.

HTH

**Comment by tino** [comment]
Ah, yes that is also a possibility. I never heard of s6 though and couldn't find the Dockerfile on your github. It might make sense to support some kind of "passthrough" in the entrypoint, as the official ones have. See for example: https://github.com/docker-library/mysql/blob/4e022c06314ff6047dabc4abee2f222ae9ce564d/5.7/docker-entrypoint.sh#L4 and L113.

**Comment by nhurel** [comment]
s6 is a supervision process which can be used as an init service (http://www.skarnet.org/software/s6/). This process is responsible of starting inbox-api and inbox-start programs.
Since this docker image is meant to only run this 2 processes, I don't see what kind of other arguments you would want to pass at startup. Could you give me some details on what you're trying to do ?

**Comment by tino** [comment]
Well, I just got some errors about databases already existing and wanted to debug from the machine itself, so I tried to get a bash shell in it (which all other containers I've used always allowed me to do). It's just an easy way to inspect of files can be found, run command by hand, etc. Basic debugging. But it's working now (after I started again with a clean mysql).
