### ISSUE TITLE
How do we update the sync engine?

### ISSUE THREAD

**Issue by elbamos** [nhurel/nylas-sync-engine#4]
Thank you for putting this all together.

How should we go about updating the sync engine?

**Comment by nhurel** [comment]
To update the sync-engine you need to stop the current running container and start a newer version of the image, linked to the same mysql database.
Then, go into the container with `docker exec -it <containername> bash` and run : `bin/migrate-db`.
This script, provided by nylas, will check if there's an upgrade to apply to the database and run it. You can run the command as long as it finds an upgrade. When your database is up to date, you should have an error message like `Relative revision +1 didn't produce 1 migrations`

Beware : The upgrade scripts sometimes fail and you have to manually manage the database migration.

**Comment by elbamos** [comment]
Is switching to the newer version of the container the same as calling docker-compose stop and docker-compose up?

**Comment by nhurel** [comment]
basically yes but `docker-compose` stop don't destroy the stopped container, so it will just restart the same instance when running `docker-compose up`. That's why I would recommend to run `docker rm` on the sync-engine container before `running docker-compose up`. 
Moreover, I don't think docker-compose will update the image so you might manually run `docker pull` before.

**Comment by elbamos** [comment]
@nhurel As of the newest N1, when I try to start I get an error that it could not reach an onboarding page on port 5009 of localhost.  Any suggestions?

**Comment by nhurel** [comment]
On my side, running n1 in version 0.4.45 I've managed to skip the N1 account creation screen by adding a "fake" identity id in config.json : 

``` js
 "nylas": {
      "identity": {
        "id": "999"
      },
      "accounts": [
        {
          ....
```

Then, new emails are synced but I can't delete none and I can't send neither. I'll stay on version 0.4.40 for the moment

**Comment by alexanderadam** [comment]
@elbamos you could also use [the branch from the open PR](https://github.com/nylas/N1/pull/2485#issuecomment-229770064).

@nhurel it should be enough to [change the volume path to something like `- ~/something-on-my/machine:/var/lib/mysql`](https://github.com/nhurel/nylas-sync-engine/blob/master/docker-compose.yml#L18) to have the data persisted, right? Somehow the directoy is empty - and it never seems to finish syncing. :cry:

**Comment by nhurel** [comment]
@alexanderadam  In the example I give, it creates a docker volume  in /var/lib/docker/volumes/nylas_mysql. So the data are actually persisted. 
But you're right, you can also specify a full path on your filesystem to tell docker to mount a specific directory as the /var/lib/mysql dir in your container

**Comment by ConorIA** [comment]
@nhurel, sorry to bump an old thread, but I thought I'd give feedback on some of the comments in this thread: 

Today I ran the following: 

```
docker-compose stop
docker rm nylassyncengine_sync-engine_1
docker pull nhurel/nylas-sync-engine
docker-compose up
```

When I accessed the container via `docker exec -it nylassyncengine_sync-engine_1 bash` and ran `bin/migrate-db`, I got the following error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/migrate-db", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/sync-engine/bin/migrate-db", line 42, in <module>
    main()
  File "/opt/sync-engine/bin/migrate-db", line 14, in main
    'Missing alembic.ini file at {}'.format(alembic_ini_filename)
AssertionError: Missing alembic.ini file at alembic.ini
```

Nevertheless, everything seems to be running smoothly, so I have no error to report. Just thought I'd share in case this is something to be worried about.

**Comment by nhurel** [comment]
@ConorIA do you `bin/migrate-db` or do you run `cd bin` and `./migrate-db` ?
The second option returns the error you indicate. Running `bin/migrate-db` from /opt/sync-engine works fine. The migrate-db script might search for the alembic.ini in current folder.

**Comment by ConorIA** [comment]
@nhurel, you're right. Yes, I was in the bin folder when I ran the `migrate-db` command. Sorry about that. Worked as expected when executed from `/opt/sync-engine`. Cheers.

Edit: In fact, if anyone stumbles on this thread looking for upgrade instructions, the following also works: 
`docker exec -it nylassyncengine_sync-engine_1 bin/migrate-db`

**Comment by fermuch** [comment]
IMO a step-by-step should be added to the README and/or a note saying what version is currently using. What do you think of that @nhurel ?

**Comment by nhurel** [comment]
Right, I've updated the documentation with upgrade instructions
