### ISSUE TITLE
Locally hosted

### ISSUE THREAD

**Issue by SFrav** [nhurel/nylas-sync-engine#6]
Does using this mean that we can avoid syncing through a third party? 

Total noob question, I know. I've wanted to use Nylas, but the external syncing was a deal breaker for me.

If so, what's the memory and processor usage like for running the sync engine locally?

**Comment by nhurel** [comment]
Yes, that's exactly why I've made this docker image :)

On my side I run it on a server with an Atom dual core @ 1.80GHz and 4Go RAM

**Comment by SFrav** [comment]
Excellent! I'll look forward to testing.
