### ISSUE TITLE
mysql exception

### ISSUE THREAD

**Issue by ParthaBoocha** [nhurel/nylas-sync-engine#8]
After using compose I was able to successfully start services and set up inbox.

But I get this when I `curl http://localhost:5555/accounts`:
{
  "message": "(_mysql_exceptions.OperationalError) (1049, \"Unknown database 'inbox_2'\")",
  "type": "api_error"
}

Any clue?

**Comment by nhurel** [comment]
Can you try logging in the sync-engine container and run `bin/create-db` as suggested here : https://github.com/nhurel/nylas-sync-engine#database-initialisation ?

**Comment by ParthaBoocha** [comment]
Thanks for the response. That fixed the problem. Not sure why it failed yesterday.
